=== ajilach/stadtwerkwinterthur/Dokumentenstruktur_generisch.dtd
<?xml version="1.0" encoding="UTF-8"?>

<!--######################## Hauptstruktur ########################-->
<!ELEMENT Dokumente ((Dokument+))>
<!ELEMENT Dokument ((Steuerinformationen, AllgemeineInfos, Dokumenteninhalt))>

<!--######################## Allgemeine Strukturen ########################-->
<!-- Adresse -->
<!ELEMENT Adresse ((Adresszeile+))>
<!ATTLIST Adresse	Rolle (Sekundärempfänger | Empfänger | Belasteter | Begünstigter | Absender) #REQUIRED>
<!ELEMENT Adresszeile (#PCDATA)>

<!-- Ausgabekanal -->
<!ELEMENT Ausgabekanal (((Emailadresse | (Druckername, Kopieanzahl) | (Archivsystem, Archivdocumentid, Archivdocumenttype))))>
<!ATTLIST Ausgabekanal	Kanalname (DruckIntern | Archiv | Email) #REQUIRED>
<!ELEMENT Kanalname (#PCDATA)>
<!ELEMENT Emailadresse (#PCDATA)>
<!ELEMENT Druckername (#PCDATA)>
<!ELEMENT Kopieanzahl (#PCDATA)>
<!ELEMENT Archivsystem (#PCDATA)>
<!ELEMENT Archivdocumenttype (#PCDATA)>
<!ELEMENT Archivdocumentid (#PCDATA)>

<!-- Infozeilen -->
<!ELEMENT Infozeilen ((Infozeile+))>
<!ELEMENT Infozeile ((InfoTitel, InfoInhalt))>
<!ELEMENT InfoTitel (#PCDATA)>
<!ATTLIST InfoTitel	Feldinfo CDATA #IMPLIED>
<!ELEMENT InfoInhalt (#PCDATA)>

<!-- Wasserzeichenliste -->
<!ELEMENT Wasserzeichen (#PCDATA)>

<!-- Funktionseintrag -->
<!ELEMENT Funktionseintrag ((Namenszeile, Funktionszeile?, Abteilungszeile?, Unterschrift?))>
<!ELEMENT Namenszeile (#PCDATA)>
<!ELEMENT Funktionszeile (#PCDATA)>
<!ELEMENT Abteilungszeile (#PCDATA)>
<!ELEMENT Unterschrift (#PCDATA)>

<!-- Beilagen -->
<!ELEMENT Beilage (#PCDATA)>

<!-- Fusszeile -->
<!ELEMENT Hinweistext (#PCDATA)>

<!-- Einzahlungsschein -->
<!-- Adressen werden im separaten Block oben abgehandelt -->
<!ELEMENT Referenznummer (#PCDATA)>
<!ELEMENT Kontonummer (#PCDATA)>
<!ELEMENT Codierzeile (#PCDATA)>
<!ELEMENT BetragRappen (#PCDATA)>
<!ELEMENT BetragFranken (#PCDATA)>

<!-- ######################## Dokumentenstruktur ########################-->
<!-- Block Steuerinformationen -->
<!ELEMENT Steuerinformationen ((Ausgabekanäle, SapSystem, SapMandant))>
<!ELEMENT Ausgabekanäle ((Ausgabekanal+))>
<!ELEMENT SapSystem (#PCDATA)>
<!ELEMENT SapMandant (#PCDATA)>

<!-- Block AllgemeineInfos -->
<!ELEMENT AllgemeineInfos ((Betreff, Adressen, Informationsblock, Wasserzeichenliste?, Grussformel?, Funktionen?, Beilagen?, Marketingtext?, Fusszeile, Einzahlungsschein?))>
<!ELEMENT Betreff (#PCDATA)>
<!ELEMENT Adressen ((Adresse+))>
<!ELEMENT Informationsblock ((Infozeilen))>
<!ELEMENT Wasserzeichenliste (Wasserzeichen+)>
<!ELEMENT Grussformel (#PCDATA)>
<!ELEMENT Funktionen ((Funktionseintrag+))>
<!ELEMENT Beilagen ((Beilage+))>
<!ELEMENT Marketingtext (#PCDATA)>
<!ELEMENT Fusszeile ((Hinweistext))>
<!ELEMENT Einzahlungsschein ((Adressen, Kontonummer, Referenznummer, Codierzeile, BetragFranken, BetragRappen))>

<!-- Block Dokumenteninhalt (formularspezifisch) -->
<!ELEMENT Dokumenteninhalt (#PCDATA)>

=== ajilach/stadtwerkwinterthur/Dokumentenstruktur_generisch.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE Dokumente SYSTEM "Dokumentenstruktur_generisch.dtd">
<Dokumente>
    <Dokument>
        <!-- Meta-Informationen zur Ausgabesteuerung -->
        <Steuerinformationen>
            <Ausgabekanäle>
                <Ausgabekanal Kanalname="DruckIntern">
                    <Druckername>Druckerbezeichnung</Druckername>
                    <Kopieanzahl>n</Kopieanzahl>
                    <!-- weitere Felder sind noch zu ergänzen -->
                </Ausgabekanal>

                <Ausgabekanal Kanalname="Archiv">
                    <ArchivOmrPrefix>*IDX1Anfang|</ArchivOmrPrefix>
                    <ArchivObjectType>PRINTDOC</ArchivObjectType>
                    <ArchivDocumentart>ISU_BILL</ArchivDocumentart>
                    <ArchivBelegnummer>8000000102</ArchivBelegnummer>
                    <ArchivVertragskontonummer>2127203</ArchivVertragskontonummer>
                    <ArchivGeschäftspartner>3127203</ArchivGeschäftspartner>
                    <ArchivBelegsdatum>16.12.2016</ArchivBelegsdatum>
                    <ArchivOmrSuffix>|GeschaeftspartnerTextNochNichtBefuellt|IDX1Ende*</ArchivOmrSuffix>
                </Ausgabekanal>

                <Ausgabekanal Kanalname="Email">
                    <Emailadresse>E-mail</Emailadresse>
                    <!-- weitere Felder sind noch zu ergänzen -->
                </Ausgabekanal>

                <Ausgabekanal Kanalname="Fax">
                    <Faxnummer>0112223344</Faxnummer>
                    <!-- weitere Felder sind noch zu ergänzen -->
                </Ausgabekanal>

                <Ausgabekanal Kanalname="Vorschau">
                    <DeckblattText>PREVIEW_BILL004105004553</DeckblattText>
                </Ausgabekanal>
            </Ausgabekanäle>

            <SapSysteminfo>
                <SapSystem>T99</SapSystem>
                <SapMandant>999</SapMandant>
                <SapUser>sapusername</SapUser>
                <SapTimestamp>2017-01-23-14.30.08.456234</SapTimestamp>
            </SapSysteminfo>

            <!-- Für die IS-U Rechnung sieht der OMR Code wie folgt aus:  -->
            <!-- OMRAnfang|ESR|Kundenid|GV_OBJID|Seitenzahl|OMREnde -->
            <OmrCode>
                <OmrPrefix>OMRAnfang|ESR|</OmrPrefix>
                <OmrKundenid>12456475</OmrKundenid>
                <OmrObjekt>00654654646846</OmrObjekt>
                <OmrSuffix>|OMREnde</OmrSuffix>
            </OmrCode>
        </Steuerinformationen>

        <!-- Formularübergreifende Strukturen -->
        <AllgemeineInfos>
            <!-- Bei der IS-U Rechnung ist dies die Rechnungsart GV_BILLTYPE -->
            <Dokumenttyp>01</Dokumenttyp>

            <!-- Bei der IS-U Rechnung ist dies der GV_STATUS -->
            <!-- Mögliche Werte: Original, Storno, Kopie, Simulation -->
            <Dokumentstatus>Original</Dokumentstatus>

            <Betreff>Betrefftext</Betreff>

            <Adressen>
                <!-- Maximal 6 Adresszeilen werden unterstützt -->
                <Adresse Rolle="Absender">
                    <Adresszeile>Absenderadresse 1</Adresszeile>
                    <Adresszeile>Absenderadresse 2</Adresszeile>
                    <Adresszeile>Absenderadresse 3</Adresszeile>
                    <Adresszeile>Absenderadresse 4</Adresszeile>
                    <Adresszeile>Absenderadresse 5</Adresszeile>
                </Adresse>

                <Adresse Rolle="Empfänger">
                    <Adresszeile>Empfängeradresse 1</Adresszeile>
                    <Adresszeile>Empfängeradresse 2</Adresszeile>
                    <Adresszeile>Empfängeradresse 3</Adresszeile>
                    <Adresszeile>Empfängeradresse 4</Adresszeile>
                    <Adresszeile>Empfängeradresse 5</Adresszeile>
                    <Adresszeile>Empfängeradresse 6</Adresszeile>
                </Adresse>
                 
                <Adresse Rolle="Sekundärempfänger">
                    <Adresszeile>Sekundäradresse 1</Adresszeile>
                    <Adresszeile>Sekundäradresse 2</Adresszeile>
                    <Adresszeile>Sekundäradresse 3</Adresszeile>
                    <Adresszeile>Sekundäradresse 4</Adresszeile>
                    <Adresszeile>Sekundäradresse 5</Adresszeile>
                </Adresse>
            </Adressen>

            <Informationsblock>
                <Infozeilen>
                    <Infozeile>
                        <InfoTitel Feldinfo="SAP Feldname 1">Feldbezeichnung 1</InfoTitel>
                        <InfoInhalt>Feldinhalt 1</InfoInhalt>
                    </Infozeile>
                    <Infozeile>
                        <InfoTitel>Feldbezeichnung 2</InfoTitel>
                        <InfoInhalt>Feldinhalt 2</InfoInhalt>
                    </Infozeile>
                </Infozeilen>
            </Informationsblock>

            <Wasserzeichenliste>
                <Wasserzeichen>Wasserzeichentext 1</Wasserzeichen>
                <Wasserzeichen>Wasserzeichentext 2</Wasserzeichen>
            </Wasserzeichenliste>

            <Grussformel>Grussformeltext</Grussformel>

            <Funktionen>
                <Funktionseintrag>
                    <Namenszeile>Namenstext 1</Namenszeile>
                    <Funktionszeile>Funktionstext 1</Funktionszeile>
                    <Abteilungszeile>Abteilungstext 1</Abteilungszeile>
                    <Unterschrift>Graphikname 1</Unterschrift>
                </Funktionseintrag>

                <Funktionseintrag>
                    <Namenszeile>Namenstext 2</Namenszeile>
                    <Funktionszeile>Funktionstext 2</Funktionszeile>
                    <Abteilungszeile>Abteilungstext 2</Abteilungszeile>
                    <Unterschrift>Graphikname 2</Unterschrift>
                </Funktionseintrag>

                <Funktionseintrag>
                    <Namenszeile>Namenstext 3</Namenszeile>
                    <Funktionszeile>Funktionstext 3</Funktionszeile>
                    <Abteilungszeile>Abteilungstext 3</Abteilungszeile>
                    <Unterschrift>Graphikname 3</Unterschrift>
                </Funktionseintrag>
            </Funktionen>
            
            <Beilagen>
                <Beilage>Beilage 1</Beilage>
                <Beilage>Beilage 2</Beilage>
                <Beilage>Beilage 3</Beilage>
            </Beilagen>

            <Marketingtext>Marketing Message</Marketingtext>

            <Fusszeile>
                <Hinweistext>Dies ist ein Hinweistext.</Hinweistext>
            </Fusszeile>

            <Einzahlungsschein>
                <Adressen>
                    <Adresse Rolle="Belasteter">
                        <Adresszeile>Empfängeradresse 1</Adresszeile>
                        <Adresszeile>Empfängeradresse 2</Adresszeile>
                        <Adresszeile>Empfängeradresse 3</Adresszeile>
                        <Adresszeile>Empfängeradresse 4</Adresszeile>
                        <Adresszeile>Empfängeradresse 5</Adresszeile>
                        <Adresszeile>Empfängeradresse 6</Adresszeile>
                        <Adresszeile>Empfängeradresse 7</Adresszeile>
                    </Adresse>

                    <Adresse Rolle="Begünstigter">
                        <Adresszeile>Empfängeradresse 1</Adresszeile>
                        <Adresszeile>Empfängeradresse 2</Adresszeile>
                        <Adresszeile>Empfängeradresse 3</Adresszeile>
                    </Adresse>
                </Adressen>

                <Kontonummer>123456</Kontonummer>
                <Referenznummer>1234567893456789</Referenznummer>
                <Codierzeile>2345678456783456789</Codierzeile>
                <BetragFranken>999</BetragFranken>
                <BetragRappen>00</BetragRappen>
            </Einzahlungsschein>
        </AllgemeineInfos>
        
        <!-- Formularspezifische Strukturen -->
        <Dokumenteninhalt>
            <!-- Tabellen, Brieftexte etc. -->
        </Dokumenteninhalt>
    </Dokument>
</Dokumente>
